// <auto-generated />
using System;
using CityAlert.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityAlert.Migrations
{
    [DbContext(typeof(CityAlertDbContext))]
    [Migration("20260331171707_AddInitialSeedData")]
    partial class AddInitialSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("CityAlert.Models.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Districts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Центр"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Пасічна"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Вовчинець"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Позитрон"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Крихівці"
                        });
                });

            modelBuilder.Entity("CityAlert.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DistrictId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            CreatedAt = new DateTime(2025, 1, 10, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "system_bot",
                            Description = "У зв'язку з аварією на вул. Галицькій, водопостачання буде відсутнє до 20:00. Працює аварійна бригада.",
                            DistrictId = 1,
                            EndDate = new DateTime(2025, 1, 11, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Severity = 2,
                            StartDate = new DateTime(2025, 1, 10, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Прорив магістрального водопроводу"
                        },
                        new
                        {
                            Id = 2,
                            Category = 3,
                            CreatedAt = new DateTime(2025, 1, 11, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "admin_moderator",
                            Description = "Через проведення дорожніх робіт автобус тимчасово курсуватиме через вул. Тролейбусну.",
                            DistrictId = 2,
                            EndDate = new DateTime(2025, 1, 15, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Severity = 1,
                            StartDate = new DateTime(2025, 1, 12, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Зміна маршруту автобуса №22"
                        },
                        new
                        {
                            Id = 3,
                            Category = 0,
                            CreatedAt = new DateTime(2025, 1, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "energy_service",
                            Description = "Ремонтні роботи на підстанції. Світла не буде у приватному секторі.",
                            DistrictId = 3,
                            EndDate = new DateTime(2025, 1, 13, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Severity = 0,
                            StartDate = new DateTime(2025, 1, 13, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Планове відключення світла"
                        },
                        new
                        {
                            Id = 4,
                            Category = 1,
                            CreatedAt = new DateTime(2025, 1, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "local_community",
                            Description = "Запрошуємо всіх мешканців на ярмарок у підтримку ЗСУ.",
                            DistrictId = 5,
                            EndDate = new DateTime(2025, 1, 20, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Severity = 0,
                            StartDate = new DateTime(2025, 1, 20, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Благодійний ярмарок"
                        },
                        new
                        {
                            Id = 5,
                            Category = 3,
                            CreatedAt = new DateTime(2025, 1, 14, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "traffic_police",
                            Description = "Аварія біля ТЦ. Рух ускладнено.",
                            DistrictId = 4,
                            EndDate = new DateTime(2025, 1, 14, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Severity = 1,
                            StartDate = new DateTime(2025, 1, 14, 15, 10, 0, 0, DateTimeKind.Unspecified),
                            Title = "ДТП на перехресті"
                        });
                });

            modelBuilder.Entity("CityAlert.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DistrictId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("UserId", "DistrictId")
                        .IsUnique();

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("CityAlert.Models.Event", b =>
                {
                    b.HasOne("CityAlert.Models.District", "District")
                        .WithMany("Events")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("CityAlert.Models.Subscription", b =>
                {
                    b.HasOne("CityAlert.Models.District", "District")
                        .WithMany("Subscriptions")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("CityAlert.Models.District", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
